locale:
  default:
    language: sv

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?useSSL=false #TODO: use SSL in production environment
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
      show_sql: true
      hbm2ddl:
        auto: update

  http:
      multipart:
        max-file-size: 128KB
        max-request-size: 128KB

dirs:
  userprofiles: Hello World!