application:
  logo:
    url: https://upload.wikimedia.org/wikipedia/commons/a/ab/Logo_TV_2015.png

dirs:
  userprofiles: /Users/erik/IdeaProjects/app/userprofiles/

#https://spring.io/guides/gs/uploading-files/